sonar.projectKey=davydfontourac_controle-de-gastos
sonar.organization=davydfontourac
sonar.language=ts
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.tsx,src/vite-env.d.ts,src/types/*,src/services/supabase.ts
sonar.cpd.exclusions=src/components/Landing/LandingTranslations.ts,src/utils/auth-translations.ts,src/pages/Changelog.tsx,src/pages/Privacy.tsx,src/pages/Terms.tsx,src/pages/Docs.tsx
